ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\DELL\AppData\Roaming
CHOCOLATEYINSTALL=C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE=133222103719773853
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_11140_PGUYTDZTFBLCWWNV
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-SD8DAQ8
COMSPEC=C:\Windows\system32\cmd.exe
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\DELL
LOCALAPPDATA=C:\Users\DELL\AppData\Local
LOGONSERVER=\\DESKTOP-SD8DAQ8
NUMBER_OF_PROCESSORS=4
ONEDRIVE=C:\Users\DELL\OneDrive - Scholars Indian School
ONEDRIVECOMMERCIAL=C:\Users\DELL\OneDrive - Scholars Indian School
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=c:\Users\DELL\.vscode\extensions\ms-python.python-2024.0.0\pythonFiles\deactivate\powershell;C:\Users\DELL\.virtualenvs\joe-UtBYg906/Scripts;c:\Users\DELL\.vscode\extensions\ms-python.python-2024.0.0\pythonFiles\deactivate\powershell;C:\Users\DELL\.virtualenvs\joe-UtBYg906/Scripts;C:\Python311\Scripts\;C:\Python311\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\DELL\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\DELL\AppData\Local\Programs\Python\Python310\;C:\Users\DELL\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\DELL\AppData\Local\Programs\Python\Python39\;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\DELL\.dotnet\tools;C:\Users\DELL\AppData\Roaming\npm;C:\Program Files\Docker\Docker\resources\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4501
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PSMODULEPATH=C:\Users\DELL\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\PROGRA~1\KMSpico\temp
TMP=C:\PROGRA~1\KMSpico\temp
USERDOMAIN=DESKTOP-SD8DAQ8
USERDOMAIN_ROAMINGPROFILE=DESKTOP-SD8DAQ8
USERNAME=DELL
USERPROFILE=C:\Users\DELL
WINDIR=C:\Windows
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.85.2
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN=c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-b43398f3cf-sock
VIRTUAL_ENV=C:\Users\DELL\.virtualenvs\joe-UtBYg906
VSCODE_INJECTION=1
